using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VumaRetail.Domain.Entities;

namespace VumaRetail.Infrastructure.Persistence.Configurations;

/// <summary>
/// Maps the columns <c>CLAUDE.md</c> §7 rule 3 puts on every table — once, here, for every entity.
/// </summary>
/// <typeparam name="TEntity">The entity being configured.</typeparam>
/// <remarks>
/// <para>
/// Rule 3 lists nine mandatory columns. Written per entity they would be right the first six times
/// and subtly wrong the seventh — a missing index, a <c>varchar(50)</c> that truncates a principal, a
/// concurrency token somebody forgot to mark. Every configuration in the solution derives from this
/// class, so there is exactly one definition of what those columns are.
/// </para>
/// <para>
/// Derived configurations supply the schema and table name and then describe only their own columns.
/// If a derived configuration ever needs to re-declare a base column, that is the signal that the
/// base is wrong, not that the entity is special.
/// </para>
/// </remarks>
public abstract class EntityConfiguration<TEntity> : IEntityTypeConfiguration<TEntity>
    where TEntity : Entity
{
    /// <summary>The module schema the table lives in. See <see cref="Schemas"/>.</summary>
    protected abstract string Schema { get; }

    /// <summary>The table name, plural and <c>snake_case</c> (<c>CONVENTIONS.md</c> §2).</summary>
    protected abstract string TableName { get; }

    /// <summary>Configures the entity. Sealed shape: base columns first, then the entity's own.</summary>
    /// <param name="builder">The entity type builder.</param>
    public void Configure(EntityTypeBuilder<TEntity> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.ToTable(TableName, Schema);

        builder.HasKey(entity => entity.Id);

        // ADR-004: UUID v7 is generated client-side so an offline terminal can create a row without a
        // round-trip. ValueGeneratedNever stops EF asking the database for a key it already has.
        builder.Property(entity => entity.Id)
            .ValueGeneratedNever();

        builder.Property(entity => entity.TenantId)
            .IsRequired();

        builder.Property(entity => entity.StoreId);

        builder.Property(entity => entity.CompanyId);
        builder.HasIndex(entity => new { entity.TenantId, entity.CompanyId })
            .HasDatabaseName($"ix_{TableName}_tenant_id_company_id");

        builder.Property(entity => entity.CreatedAt)
            .IsRequired();

        builder.Property(entity => entity.CreatedBy)
            .IsRequired()
            .HasMaxLength(PrincipalMaxLength);

        builder.Property(entity => entity.UpdatedAt)
            .IsRequired();

        builder.Property(entity => entity.UpdatedBy)
            .IsRequired()
            .HasMaxLength(PrincipalMaxLength);

        // ADR-003 + §7 rule 3: an application-generated bytea token rather than PostgreSQL's xmin.
        // The same entities are cached in SQLite on every terminal, and SQLite has no xmin — one
        // concurrency token shape has to work on both tiers or sync compares different things at each
        // end. AuditInterceptor writes a fresh token on every insert and update. See ADR-035.
        builder.Property(entity => entity.RowVersion)
            .IsRequired()
            .IsConcurrencyToken()
            .HasColumnType("bytea");

        builder.Property(entity => entity.SyncState)
            .IsRequired()
            .HasConversion<string>()
            .HasMaxLength(32);

        // ADR-007: every replicated row carries a hybrid logical clock stamp. Stored in the sortable
        // string form so an ordinal index sorts it the same way HlcStamp compares it — which is what
        // lets a cursor be one indexed column instead of three.
        builder.Property(entity => entity.SyncStamp)
            .IsRequired()
            .HasMaxLength(SyncStampMaxLength);

        builder.Property(entity => entity.DeletedAt);

        builder.Property(entity => entity.DeletedBy)
            .HasMaxLength(PrincipalMaxLength);

        // Every query filters on tenant, and most filter on store. Without these two indexes the
        // filters that make isolation automatic also make every query a sequential scan.
        builder.HasIndex(entity => entity.TenantId)
            .HasDatabaseName($"ix_{TableName}_tenant_id");

        builder.HasIndex(entity => new { entity.TenantId, entity.StoreId })
            .HasDatabaseName($"ix_{TableName}_tenant_id_store_id");

        // The sync dispatcher's hot query is "what is still pending on this node" (ADR-006). Partial,
        // because Synced rows are the overwhelming majority and indexing them wastes the index.
        builder.HasIndex(entity => entity.SyncState)
            .HasDatabaseName($"ix_{TableName}_sync_state")
            .HasFilter("sync_state <> 'Synced'");

        ConfigureEntity(builder);
    }

    /// <summary>The maximum length of a principal string. Shaped <c>user:{uuid}</c> or <c>system:{component}</c>.</summary>
    private const int PrincipalMaxLength = 128;

    /// <summary>
    /// The maximum length of a stamp: 14 digits, 6 digits, two separators and a node id.
    /// </summary>
    private const int SyncStampMaxLength = 14 + 1 + 6 + 1 + Domain.Primitives.HlcStamp.NodeIdMaxLength;

    /// <summary>Configures the columns specific to this entity.</summary>
    /// <param name="builder">The entity type builder, with the base columns already mapped.</param>
    protected abstract void ConfigureEntity(EntityTypeBuilder<TEntity> builder);
}
