using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VumaRetail.Infrastructure.Migrations;

public partial class Stage25_26_HrWorkforce : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.Sql("CREATE SCHEMA IF NOT EXISTS hr_management; CREATE SCHEMA IF NOT EXISTS hr_workforce;");
        m.Sql(@"CREATE TABLE hr_management.employees (id uuid PRIMARY KEY, employee_number varchar(32) NOT NULL, first_name varchar(128) NOT NULL, last_name varchar(128) NOT NULL, preferred_name varchar(128), email varchar(256), phone varchar(32), hired_at timestamptz NOT NULL, terminated_at timestamptz, employment_type varchar(32) NOT NULL, status varchar(32) NOT NULL, tenant_id uuid NOT NULL, store_id uuid, company_id uuid NOT NULL, created_at timestamptz NOT NULL, created_by varchar(128) NOT NULL, updated_at timestamptz NOT NULL, updated_by varchar(128) NOT NULL, row_version bytea NOT NULL, sync_state varchar(32) NOT NULL, sync_stamp varchar(86) NOT NULL, deleted_at timestamptz, deleted_by varchar(128));");
        m.Sql(@"CREATE TABLE hr_management.employment_contracts (id uuid PRIMARY KEY, employee_id uuid NOT NULL, starts_on date NOT NULL, ends_on date, hourly_rate numeric(19,4) NOT NULL, currency varchar(3) NOT NULL, tenant_id uuid NOT NULL, store_id uuid, company_id uuid NOT NULL, created_at timestamptz NOT NULL, created_by varchar(128) NOT NULL, updated_at timestamptz NOT NULL, updated_by varchar(128) NOT NULL, row_version bytea NOT NULL, sync_state varchar(32) NOT NULL, sync_stamp varchar(86) NOT NULL, deleted_at timestamptz, deleted_by varchar(128));");
        m.Sql(@"CREATE TABLE hr_management.leave_requests (id uuid PRIMARY KEY, employee_id uuid NOT NULL, ""from"" date NOT NULL, ""to"" date NOT NULL, leave_type varchar(64) NOT NULL, reason varchar(1000), status varchar(32) NOT NULL, decided_at timestamptz, tenant_id uuid NOT NULL, store_id uuid, company_id uuid NOT NULL, created_at timestamptz NOT NULL, created_by varchar(128) NOT NULL, updated_at timestamptz NOT NULL, updated_by varchar(128) NOT NULL, row_version bytea NOT NULL, sync_state varchar(32) NOT NULL, sync_stamp varchar(86) NOT NULL, deleted_at timestamptz, deleted_by varchar(128));");
        m.Sql(@"CREATE TABLE hr_workforce.shifts (id uuid PRIMARY KEY, employee_id uuid NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, role varchar(128) NOT NULL, status varchar(32) NOT NULL, tenant_id uuid NOT NULL, store_id uuid, company_id uuid NOT NULL, created_at timestamptz NOT NULL, created_by varchar(128) NOT NULL, updated_at timestamptz NOT NULL, updated_by varchar(128) NOT NULL, row_version bytea NOT NULL, sync_state varchar(32) NOT NULL, sync_stamp varchar(86) NOT NULL, deleted_at timestamptz, deleted_by varchar(128));");
        m.Sql(@"CREATE TABLE hr_workforce.attendance_records (id uuid PRIMARY KEY, employee_id uuid NOT NULL, shift_id uuid, event_type varchar(32) NOT NULL, occurred_at timestamptz NOT NULL, source varchar(64), tenant_id uuid NOT NULL, store_id uuid, company_id uuid NOT NULL, created_at timestamptz NOT NULL, created_by varchar(128) NOT NULL, updated_at timestamptz NOT NULL, updated_by varchar(128) NOT NULL, row_version bytea NOT NULL, sync_state varchar(32) NOT NULL, sync_stamp varchar(86) NOT NULL, deleted_at timestamptz, deleted_by varchar(128));");
        m.Sql("CREATE UNIQUE INDEX ux_employees_tenant_id_employee_number ON hr_management.employees(tenant_id, employee_number) WHERE deleted_at IS NULL; CREATE UNIQUE INDEX ux_employment_contracts_tenant_employee_start ON hr_management.employment_contracts(tenant_id, employee_id, starts_on) WHERE deleted_at IS NULL; CREATE INDEX ix_leave_requests_tenant_employee_from ON hr_management.leave_requests(tenant_id, employee_id, \"from\"); CREATE INDEX ix_shifts_tenant_employee_starts ON hr_workforce.shifts(tenant_id, employee_id, starts_at); CREATE INDEX ix_attendance_records_tenant_employee_occurred ON hr_workforce.attendance_records(tenant_id, employee_id, occurred_at);");
        foreach (var (table, schema) in new[] { ("employees", "hr_management"), ("employment_contracts", "hr_management"), ("leave_requests", "hr_management"), ("shifts", "hr_workforce"), ("attendance_records", "hr_workforce") })
            m.Sql($"CREATE INDEX ix_{table}_tenant_id ON {schema}.{table}(tenant_id); CREATE INDEX ix_{table}_tenant_id_company_id ON {schema}.{table}(tenant_id, company_id); CREATE INDEX ix_{table}_tenant_id_store_id ON {schema}.{table}(tenant_id, store_id); CREATE INDEX ix_{table}_sync_state ON {schema}.{table}(sync_state) WHERE sync_state <> 'Synced';");
    }

    protected override void Down(MigrationBuilder m) => m.Sql("DROP TABLE IF EXISTS hr_workforce.attendance_records; DROP TABLE IF EXISTS hr_workforce.shifts; DROP TABLE IF EXISTS hr_management.leave_requests; DROP TABLE IF EXISTS hr_management.employment_contracts; DROP TABLE IF EXISTS hr_management.employees;");
}
