using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VumaRetail.Infrastructure.Persistence;

namespace VumaRetail.Infrastructure.RegistryMigrations;

[DbContext(typeof(VumaRegistryDbContext))]
[Migration("20260828100000_RegistryGroupsAndSagas")]
public partial class RegistryGroupsAndSagas : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.EnsureSchema("registry");
        m.CreateTable("company_groups", t => new { id = t.Column<Guid>("uuid", nullable: false), tenant_id = t.Column<Guid>("uuid", nullable: false), name = t.Column<string>("character varying(200)", maxLength: 200, nullable: false) }, schema: "registry", constraints: c => c.PrimaryKey("pk_company_groups", x => x.id));
        m.CreateTable("saga_intents", t => new { id = t.Column<Guid>("uuid", nullable: false), tenant_id = t.Column<Guid>("uuid", nullable: false), type = t.Column<string>("character varying(128)", maxLength: 128, nullable: false), idempotency_key = t.Column<string>("character varying(256)", maxLength: 256, nullable: false), payload = t.Column<string>("jsonb", nullable: false), state = t.Column<string>("character varying(16)", maxLength: 16, nullable: false), created_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: false), expires_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: true), owner = t.Column<string>("character varying(128)", maxLength: 128, nullable: true), authorized_operator_id = t.Column<Guid>("uuid", nullable: true), initiated_by = t.Column<string>("character varying(128)", maxLength: 128, nullable: false), operation_stamp = t.Column<string>("character varying(128)", maxLength: 128, nullable: false) }, schema: "registry", constraints: c => c.PrimaryKey("pk_saga_intents", x => x.id));
        m.CreateTable("company_group_members", t => new { tenant_id = t.Column<Guid>("uuid", nullable: false), group_id = t.Column<Guid>("uuid", nullable: false), company_id = t.Column<Guid>("uuid", nullable: false) }, schema: "registry", constraints: c => { c.PrimaryKey("pk_company_group_members", x => new { x.group_id, x.company_id }); c.ForeignKey(name: "fk_company_group_members_company_groups_group_id", columns: x => new { x.tenant_id, x.group_id }, principalSchema: "registry", principalTable: "company_groups", principalColumns: new[] { "tenant_id", "id" }, onDelete: ReferentialAction.Cascade); c.ForeignKey(name: "fk_company_group_members_companies_company_id", columns: x => new { x.tenant_id, x.company_id }, principalSchema: "registry", principalTable: "companies", principalColumns: new[] { "tenant_id", "id" }, onDelete: ReferentialAction.Restrict); });
        m.CreateTable("saga_legs", t => new { tenant_id = t.Column<Guid>("uuid", nullable: false), intent_id = t.Column<Guid>("uuid", nullable: false), leg_id = t.Column<Guid>("uuid", nullable: false), company_id = t.Column<Guid>("uuid", nullable: false), state = t.Column<string>("character varying(16)", maxLength: 16, nullable: false), attempts = t.Column<int>("integer", nullable: false), acknowledged_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: true), timed_out_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: true), last_error = t.Column<string>("character varying(1024)", maxLength: 1024, nullable: true), last_attempt_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: true), operation_stamp = t.Column<string>("character varying(128)", maxLength: 128, nullable: false) }, schema: "registry", constraints: c => { c.PrimaryKey("pk_saga_legs", x => new { x.intent_id, x.leg_id }); c.ForeignKey(name: "fk_saga_legs_saga_intents_intent_id", columns: x => new { x.tenant_id, x.intent_id }, principalSchema: "registry", principalTable: "saga_intents", principalColumns: new[] { "tenant_id", "id" }, onDelete: ReferentialAction.Cascade); c.ForeignKey(name: "fk_saga_legs_companies_company_id", columns: x => new { x.tenant_id, x.company_id }, principalSchema: "registry", principalTable: "companies", principalColumns: new[] { "tenant_id", "id" }, onDelete: ReferentialAction.Restrict); });
        m.CreateTable("outbox_messages", t => new { id = t.Column<Guid>("uuid", nullable: false), tenant_id = t.Column<Guid>("uuid", nullable: false), type = t.Column<string>("character varying(128)", maxLength: 128, nullable: false), payload = t.Column<string>("jsonb", nullable: false), idempotency_key = t.Column<string>("character varying(256)", maxLength: 256, nullable: false), created_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: false), dispatched_at = t.Column<DateTimeOffset>("timestamp with time zone", nullable: true), attempts = t.Column<int>("integer", nullable: false), operation_stamp = t.Column<string>("character varying(128)", maxLength: 128, nullable: false) }, schema: "registry", constraints: c => c.PrimaryKey("pk_registry_outbox_messages", x => x.id));
        m.CreateIndex("ux_company_groups_tenant_name", "company_groups", new[] { "tenant_id", "name" }, unique: true, schema: "registry");
        m.CreateIndex("ux_company_groups_tenant_id", "company_groups", new[] { "tenant_id", "id" }, unique: true, schema: "registry");
        m.CreateIndex("ux_companies_tenant_id", "companies", new[] { "tenant_id", "id" }, unique: true, schema: "registry");
        m.CreateIndex("ux_saga_intents_tenant_idempotency_key", "saga_intents", new[] { "tenant_id", "idempotency_key" }, unique: true, schema: "registry");
        m.CreateIndex("ux_saga_intents_tenant_id", "saga_intents", new[] { "tenant_id", "id" }, unique: true, schema: "registry");
        m.CreateIndex("ix_saga_intents_tenant_state_created_at", "saga_intents", new[] { "tenant_id", "state", "created_at" }, schema: "registry");
        m.CreateIndex("ix_saga_legs_company_state", "saga_legs", new[] { "company_id", "state" }, schema: "registry");
        m.CreateIndex("ix_registry_outbox_tenant_dispatched_created", "outbox_messages", new[] { "tenant_id", "dispatched_at", "created_at" }, schema: "registry");
        m.CreateIndex("ux_registry_outbox_tenant_idempotency_key", "outbox_messages", new[] { "tenant_id", "idempotency_key" }, unique: true, schema: "registry");
    }
    protected override void Down(MigrationBuilder m)
    { m.DropTable("saga_legs", "registry"); m.DropTable("company_group_members", "registry"); m.DropTable("outbox_messages", "registry"); m.DropTable("saga_intents", "registry"); m.DropTable("company_groups", "registry"); }
}
