// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VumaRetail.Infrastructure.Persistence;

#nullable disable

namespace VumaRetail.Infrastructure.RegistryMigrations
{
    [DbContext(typeof(VumaRegistryDbContext))]
    [Migration("20260904063758_SyncRegistryModelChanges")]
    partial class SyncRegistryModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VumaRetail.Domain.Registry.CatalogRoutingIndexEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_at");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("company_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("item_code");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_catalog_routing_index");

                    b.HasIndex("TenantId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_catalog_routing_index_tenant_id_barcode");

                    b.HasIndex("TenantId", "CompanyId", "Barcode")
                        .HasDatabaseName("ix_catalog_routing_index_tenant_id_company_id_barcode");

                    b.ToTable("catalog_routing_index", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionSecretRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("connection_secret_ref");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deactivated_by");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deactivation_reason");

                    b.Property<string>("DocumentPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_prefix");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("locale");

                    b.Property<string>("MigrationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("migration_state");

                    b.Property<int>("ProvisioningAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("provisioning_attempts");

                    b.Property<string>("ProvisioningError")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provisioning_error");

                    b.Property<string>("ProvisioningStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provisioning_step");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registration_number");

                    b.Property<long>("SchemaVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("schema_version");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trading_name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_companies_tenant_id_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_id_code");

                    b.HasIndex("TenantId", "DocumentPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_id_document_prefix");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_companies_tenant_id_is_active");

                    b.ToTable("companies", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_companies_active_requires_active_state", "NOT is_active OR lifecycle_state = 'Active'");

                            t.HasCheckConstraint("ck_companies_active_requires_secret", "NOT is_active OR connection_secret_ref IS NOT NULL");

                            t.HasCheckConstraint("ck_companies_lifecycle_state", "lifecycle_state IN ('Provisioning', 'Seeding', 'Registered', 'Active', 'Deactivated')");
                        });
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_company_groups");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_company_groups_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_company_groups_tenant_id_name");

                    b.ToTable("company_groups", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroupMember", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.HasKey("TenantId", "GroupId", "CompanyId")
                        .HasName("pk_company_group_members");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_company_group_members_tenant_id_company_id");

                    b.ToTable("company_group_members", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyLifecycleAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_company_lifecycle_audits");

                    b.HasIndex("TenantId", "CompanyId", "OccurredAt")
                        .HasDatabaseName("ix_company_lifecycle_audits_tenant_id_company_id_occurred_at");

                    b.ToTable("company_lifecycle_audits", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<bool>("AcceptedByA")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_by_a");

                    b.Property<bool>("AcceptedByB")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted_by_b");

                    b.Property<Guid>("CompanyAId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_a_id");

                    b.Property<Guid>("CompanyBId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_b_id");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int>("Scopes")
                        .HasColumnType("integer")
                        .HasColumnName("scopes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspendedReason")
                        .HasColumnType("text")
                        .HasColumnName("suspended_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_company_links");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_company_links_tenant_id_status");

                    b.HasIndex("TenantId", "CompanyAId", "CompanyBId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_links_tenant_id_company_a_id_company_b_id");

                    b.ToTable("company_links", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditExposureEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("CreditGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_group_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("document_reference");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_exposure_entries");

                    b.HasIndex("TenantId", "CreditGroupId", "CompanyId")
                        .HasDatabaseName("ix_credit_exposure_entries_tenant_id_credit_group_id_company_id");

                    b.ToTable("credit_exposure_entries", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_groups");

                    b.ToTable("credit_groups", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditGroupMember", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("CreditGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_group_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("SubLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_limit");

                    b.HasKey("TenantId", "CreditGroupId", "CompanyId")
                        .HasName("pk_credit_group_members");

                    b.HasIndex("CreditGroupId")
                        .HasDatabaseName("ix_credit_group_members_credit_group_id");

                    b.ToTable("credit_group_members", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("CreditGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_group_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DocumentReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("document_reference");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_holds");

                    b.HasIndex("TenantId", "CreditGroupId", "State")
                        .HasDatabaseName("ix_credit_holds_tenant_id_credit_group_id_state");

                    b.ToTable("credit_holds", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.RegistryOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("OperationStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_stamp");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_tenant_id_idempotency_key");

                    b.HasIndex("TenantId", "DispatchedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_dispatched_at_created_at");

                    b.ToTable("outbox_messages", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorizedOperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorized_operator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("initiated_by");

                    b.Property<string>("OperationStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_stamp");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_saga_intents");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_saga_intents_tenant_id_id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_saga_intents_tenant_id_idempotency_key");

                    b.HasIndex("TenantId", "State", "CreatedAt")
                        .HasDatabaseName("ix_saga_intents_tenant_id_state_created_at");

                    b.ToTable("saga_intents", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaLeg", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<Guid>("LegId")
                        .HasColumnType("uuid")
                        .HasColumnName("leg_id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<string>("OperationStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("operation_stamp");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TimedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timed_out_at");

                    b.HasKey("TenantId", "IntentId", "LegId")
                        .HasName("pk_saga_legs");

                    b.HasIndex("CompanyId", "State")
                        .HasDatabaseName("ix_saga_legs_company_id_state");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasDatabaseName("ix_saga_legs_tenant_id_company_id");

                    b.ToTable("saga_legs", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroupMember", b =>
                {
                    b.HasOne("VumaRetail.Domain.Registry.Company", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_group_members_companies_tenant_id_company_id");

                    b.HasOne("VumaRetail.Domain.Registry.CompanyGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("TenantId", "GroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_group_members_company_groups_tenant_id_group_id");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditGroupMember", b =>
                {
                    b.HasOne("VumaRetail.Domain.Registry.CreditGroup", null)
                        .WithMany("Members")
                        .HasForeignKey("CreditGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_group_members_credit_groups_credit_group_id");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaLeg", b =>
                {
                    b.HasOne("VumaRetail.Domain.Registry.Company", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saga_legs_companies_tenant_id_company_id");

                    b.HasOne("VumaRetail.Domain.Registry.SagaIntent", null)
                        .WithMany("Legs")
                        .HasForeignKey("TenantId", "IntentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saga_legs_saga_intents_tenant_id_intent_id");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CreditGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaIntent", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
