// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VumaRetail.Infrastructure.Persistence.Registry;

#nullable disable

namespace VumaRetail.Infrastructure.Migrations.Registry
{
    [DbContext(typeof(VumaRegistryDbContext))]
    [Migration("20260823204852_InitialRegistry")]
    partial class InitialRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_company_groups");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_company_groups_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_company_groups_tenant_id");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_company_groups_tenant_id_store_id");

                    b.ToTable("company_groups", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.CompanyGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_group_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("MemberCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_company_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_company_group_members");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_company_group_members_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_company_group_members_tenant_id");

                    b.HasIndex("CompanyGroupId", "MemberCompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_company_group_members_group_id_company_id")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_company_group_members_tenant_id_store_id");

                    b.ToTable("company_group_members", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.RegistryCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("base_currency")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DocumentPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("document_prefix");

                    b.Property<string>("FailedStep")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failed_step");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("MigrationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("migration_state");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("registration_number");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("schema_version");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("trading_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_companies_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_companies_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_tenant_id_code")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_companies_tenant_id_store_id");

                    b.HasIndex("TenantId", "LifecycleState", "IsActive")
                        .HasDatabaseName("ix_companies_tenant_id_lifecycle_state_is_active");

                    b.ToTable("companies", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.RegistryOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("message_kind");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<Guid?>("TargetCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_company_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_messages_operation_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_outbox_messages_status")
                        .HasFilter("status <> 'Dispatched'");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_outbox_messages_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_store_id");

                    b.ToTable("outbox_messages", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_saga_intents");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_saga_intents_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_saga_intents_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_saga_intents_tenant_id_status");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_saga_intents_tenant_id_store_id");

                    b.ToTable("saga_intents", "registry");
                });

            modelBuilder.Entity("VumaRetail.Domain.Registry.SagaLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<string>("LegKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("leg_key");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<string>("SyncStamp")
                        .IsRequired()
                        .HasMaxLength(86)
                        .HasColumnType("character varying(86)")
                        .HasColumnName("sync_stamp");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sync_state");

                    b.Property<Guid>("TargetCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_company_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_saga_legs");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("ix_saga_legs_sync_state")
                        .HasFilter("sync_state <> 'Synced'");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_saga_legs_tenant_id");

                    b.HasIndex("IntentId", "LegKey")
                        .IsUnique()
                        .HasDatabaseName("ux_saga_legs_intent_id_leg_key");

                    b.HasIndex("TargetCompanyId", "Status")
                        .HasDatabaseName("ix_saga_legs_target_company_id_status");

                    b.HasIndex("TenantId", "StoreId")
                        .HasDatabaseName("ix_saga_legs_tenant_id_store_id");

                    b.ToTable("saga_legs", "registry");
                });
#pragma warning restore 612, 618
        }
    }
}
